### ISSUE TITLE
Qt 5.12 support?

### ISSUE THREAD

**Issue by eric1lubow** [blackSnack/QML-AntDesign#4]
Most Qt developers are using Qt 5.12+. Can this project support version 5.12+?

**Comment by blackSnack** [comment]
Yes, the project plan needs to support Qt5 and Qt6, but the current CMake configuration only applies to Qt6, I will create a pull request to support Qt5.

Required:
1. Support Qt5.12+
2. Add Qt5 action

**Comment by blackSnack** [comment]
The Qt5 build project is now supported. If both Qt5 and Qt6 exist in your environment, set QT_DEFAULT_MAJOR_VERSION to 5 or 6 in order to generate the CMake project.
